/*******************************************************************************
*
*  (C) COPYRIGHT AUTHORS, 2015 - 2019
*
*  TITLE:       PROPSECURITYCONSTS.H
*
*  VERSION:     1.82
*
*  DATE:        13 Nov 2019
*
*  Consts header file for Security property sheet.
*
* THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
* ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED
* TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
* PARTICULAR PURPOSE.
*
*******************************************************************************/
#pragma once

/********************************************************************************
*
* Access values for supported types
*
*********************************************************************************/

#define SI_ACCESS_DEFAULT_FLAGS SI_ACCESS_GENERAL | SI_ACCESS_SPECIFIC

//
//General Access Values
//
#define MAX_KNOWN_GENERAL_ACCESS_VALUE 5
static SI_ACCESS GeneralAccessValues[MAX_KNOWN_GENERAL_ACCESS_VALUE] = {
    { &GUID_NULL, DELETE, L"Delete", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, READ_CONTROL, L"Read Control", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, WRITE_DAC, L"Write DAC", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, WRITE_OWNER, L"Write Owner", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, SYNCHRONIZE, L"Synchronize", SI_ACCESS_DEFAULT_FLAGS }
};

//
//Section Access Values
//
#define MAX_KNOWN_SECTION_ACCESS_VALUE 5
static SI_ACCESS SectionAccessValues[MAX_KNOWN_SECTION_ACCESS_VALUE] = {
    { &GUID_NULL, SECTION_QUERY, L"Query", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, SECTION_MAP_WRITE, L"Map Write", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, SECTION_MAP_READ, L"Map Read", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, SECTION_MAP_EXECUTE, L"Map Execute", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, SECTION_EXTEND_SIZE, L"Extend Size", SI_ACCESS_DEFAULT_FLAGS }
};

//
//Directory Access Values
//
#define MAX_KNOWN_DIRECTORY_ACCESS_VALUE 4
static SI_ACCESS DirectoryAccessValues[MAX_KNOWN_DIRECTORY_ACCESS_VALUE] = {
    { &GUID_NULL, DIRECTORY_QUERY, L"Query", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, DIRECTORY_TRAVERSE, L"Traverse", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, DIRECTORY_CREATE_OBJECT, L"Create Object", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, DIRECTORY_CREATE_SUBDIRECTORY, L"Create SubDirectory", SI_ACCESS_DEFAULT_FLAGS }
};

//
//File Access Values
//
#define MAX_KNOWN_FILE_ACCESS_VALUE 14
static SI_ACCESS FileAccessValues[MAX_KNOWN_FILE_ACCESS_VALUE] = {
    { &GUID_NULL, FILE_READ_DATA, L"Read Data", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, FILE_LIST_DIRECTORY, L"List Directory", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, FILE_WRITE_DATA, L"Write Data", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, FILE_ADD_FILE, L"Add File", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, FILE_APPEND_DATA, L"Append Data", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, FILE_ADD_SUBDIRECTORY, L"Add SubDirectory", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, FILE_CREATE_PIPE_INSTANCE, L"Create Pipe Instance", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, FILE_READ_EA, L"Read EA", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, FILE_WRITE_EA, L"Write EA", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, FILE_EXECUTE, L"Execute", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, FILE_TRAVERSE, L"Traverse", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, FILE_DELETE_CHILD, L"Delete Child", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, FILE_READ_ATTRIBUTES, L"Read Attributes", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, FILE_WRITE_ATTRIBUTES, L"Write Attributes", SI_ACCESS_DEFAULT_FLAGS }
};

//
//Event Access Values
//
#define MAX_KNOWN_EVENT_ACCESS_VALUE 2
static SI_ACCESS EventAccessValues[MAX_KNOWN_EVENT_ACCESS_VALUE] = {
    { &GUID_NULL, EVENT_QUERY_STATE, L"Query State", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, EVENT_MODIFY_STATE, L"Modify State", SI_ACCESS_DEFAULT_FLAGS }
};


//
//Mutant Access Values
//
#define MAX_KNOWN_MUTANT_ACCESS_VALUE 1
static SI_ACCESS MutantAccessValues[MAX_KNOWN_MUTANT_ACCESS_VALUE] = {
    { &GUID_NULL, MUTANT_QUERY_STATE, L"Query State", SI_ACCESS_DEFAULT_FLAGS }
};

//
//Desktop Access Values
//
#define MAX_KNOWN_DESKTOP_ACCESS_VALUE 9
static SI_ACCESS DesktopAccessValues[MAX_KNOWN_DESKTOP_ACCESS_VALUE] = {
    { &GUID_NULL, DESKTOP_READOBJECTS, L"Read Objects", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, DESKTOP_CREATEWINDOW, L"Create Window", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, DESKTOP_CREATEMENU, L"Create Menu", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, DESKTOP_HOOKCONTROL, L"Hook Control", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, DESKTOP_JOURNALRECORD, L"Journal Record", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, DESKTOP_JOURNALPLAYBACK, L"Journal Playback", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, DESKTOP_ENUMERATE, L"Enumerate", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, DESKTOP_WRITEOBJECTS, L"WriteObjects", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, DESKTOP_SWITCHDESKTOP, L"Switch Desktop", SI_ACCESS_DEFAULT_FLAGS }
};

//
//WinStation Access Values
//
#define MAX_KNOWN_WINSTATION_ACCESS_VALUE 9
static SI_ACCESS WinStationAccessValues[MAX_KNOWN_WINSTATION_ACCESS_VALUE] = {
    { &GUID_NULL, WINSTA_ENUMDESKTOPS, L"Enumerate Desktops", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, WINSTA_READATTRIBUTES, L"Read Attributes", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, WINSTA_ACCESSCLIPBOARD, L"Access Clipboard", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, WINSTA_CREATEDESKTOP, L"Create Desktop", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, WINSTA_WRITEATTRIBUTES, L"Write Attributes", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, WINSTA_ACCESSGLOBALATOMS, L"Access Global Atoms", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, WINSTA_EXITWINDOWS, L"Exit Windows", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, WINSTA_ENUMERATE, L"Enumerate", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, WINSTA_READSCREEN, L"Read Screen", SI_ACCESS_DEFAULT_FLAGS }
};

//
//Key Access Values
//
#define MAX_KNOWN_KEY_ACCESS_VALUE 8
static SI_ACCESS KeyAccessValues[MAX_KNOWN_KEY_ACCESS_VALUE] = {
    { &GUID_NULL, KEY_QUERY_VALUE, L"Query Value", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, KEY_SET_VALUE, L"Set Value", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, KEY_CREATE_SUB_KEY, L"Create Subkey", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, KEY_ENUMERATE_SUB_KEYS, L"Enumerate Subkeys", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, KEY_NOTIFY, L"Notify", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, KEY_CREATE_LINK, L"Create Link", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, KEY_WOW64_64KEY, L"Access 64 bit key", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, KEY_WOW64_32KEY, L"Access 32 bit key", SI_ACCESS_DEFAULT_FLAGS }
};

//
//Semaphore Access Values
//
#define MAX_KNOWN_SEMAPHORE_ACCESS_VALUE 2
static SI_ACCESS SemaphoreAccessValues[MAX_KNOWN_SEMAPHORE_ACCESS_VALUE] = {
    { &GUID_NULL, SEMAPHORE_QUERY_STATE, L"Query State", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, SEMAPHORE_MODIFY_STATE, L"Modify State", SI_ACCESS_DEFAULT_FLAGS }
};

//
//Symlink Access Values
//
#define MAX_KNOWN_SYMLINK_ACCESS_VALUE 1
static SI_ACCESS SymlinkAccessValues[MAX_KNOWN_SYMLINK_ACCESS_VALUE] = {
    { &GUID_NULL, SYMBOLIC_LINK_QUERY, L"Link Query", SI_ACCESS_DEFAULT_FLAGS }
};

//
//Timer Access Values
//
#define MAX_KNOWN_TIMER_ACCESS_VALUE 2
static SI_ACCESS TimerAccessValues[MAX_KNOWN_TIMER_ACCESS_VALUE] = {
    { &GUID_NULL, TIMER_QUERY_STATE, L"Query State", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, TIMER_MODIFY_STATE, L"Modify State", SI_ACCESS_DEFAULT_FLAGS }
};

//
//Job Access Values
//
#define MAX_KNOWN_JOB_ACCESS_VALUE 5
static SI_ACCESS JobAccessValues[MAX_KNOWN_JOB_ACCESS_VALUE] = {
    { &GUID_NULL, JOB_OBJECT_ASSIGN_PROCESS, L"Assign Process", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, JOB_OBJECT_SET_ATTRIBUTES, L"Set Attributes", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, JOB_OBJECT_QUERY, L"Query", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, JOB_OBJECT_TERMINATE, L"Terminate", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, JOB_OBJECT_SET_SECURITY_ATTRIBUTES, L"Set Security Attributes", SI_ACCESS_DEFAULT_FLAGS }
};

//
//Port Access Values
//
#define MAX_KNOWN_PORT_ACCESS_VALUE 1
static SI_ACCESS PortAccessValues[MAX_KNOWN_PORT_ACCESS_VALUE] = {
    { &GUID_NULL, PORT_CONNECT, L"Connect", SI_ACCESS_DEFAULT_FLAGS }
};

//
//Session Access Values
//
#define MAX_KNOWN_SESSION_ACCESS_VALUE 2
static SI_ACCESS SessionAccessValues[MAX_KNOWN_SESSION_ACCESS_VALUE] = {
    { &GUID_NULL, SESSION_QUERY_ACCESS, L"Query", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, SESSION_MODIFY_ACCESS, L"Modify", SI_ACCESS_DEFAULT_FLAGS }
};

//
//IoCompletion Access Values
//
#define MAX_KNOWN_IOCOMPLETION_ACCESS_VALUE 2
static SI_ACCESS IoCompletionAccessValues[MAX_KNOWN_IOCOMPLETION_ACCESS_VALUE] = {
    { &GUID_NULL, IO_COMPLETION_QUERY_STATE, L"Query State", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, IO_COMPLETION_MODIFY_STATE, L"Modify State", SI_ACCESS_DEFAULT_FLAGS }
};

//
//MemoryPartition Access Values
//
#define MAX_KNOWN_MEMORYPARTITION_ACCESS_VALUE 2
static SI_ACCESS MemoryPartitionAccessValues[MAX_KNOWN_MEMORYPARTITION_ACCESS_VALUE] = {
    { &GUID_NULL, MEMORY_PARTITION_QUERY_ACCESS, L"Query", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, MEMORY_PARTITION_MODIFY_ACCESS, L"Modify", SI_ACCESS_DEFAULT_FLAGS }
};

//
//Process Access Values
//
#define MAX_KNOWN_PROCESS_ACCESS_VALUE 14
static SI_ACCESS ProcessAccessValues[MAX_KNOWN_PROCESS_ACCESS_VALUE] = {
    { &GUID_NULL, PROCESS_TERMINATE, L"Terminate", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, PROCESS_CREATE_THREAD, L"Create Thread", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, PROCESS_SET_SESSIONID, L"Set Session Id", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, PROCESS_VM_OPERATION, L"VM Operation", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, PROCESS_VM_READ, L"VM Read", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, PROCESS_VM_WRITE, L"VM Write", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, PROCESS_DUP_HANDLE, L"Duplicate Handle", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, PROCESS_CREATE_PROCESS, L"Create Process", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, PROCESS_SET_QUOTA, L"Set Quota", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, PROCESS_SET_INFORMATION, L"Set Information", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, PROCESS_QUERY_INFORMATION, L"Query Information", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, PROCESS_SUSPEND_RESUME, L"Suspend Resume", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, PROCESS_QUERY_LIMITED_INFORMATION, L"Query Limited Information", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, PROCESS_SET_LIMITED_INFORMATION, L"Set Limited Information", SI_ACCESS_DEFAULT_FLAGS }
};

//
//Thread Access Values
//
#define MAX_KNOWN_THREAD_ACCESS_VALUE 13
static SI_ACCESS ThreadAccessValues[MAX_KNOWN_THREAD_ACCESS_VALUE] = {
    { &GUID_NULL, THREAD_TERMINATE, L"Terminate", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, THREAD_SUSPEND_RESUME, L"Suspend Resume", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, THREAD_ALERT, L"Alert", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, THREAD_GET_CONTEXT, L"Get Context", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, THREAD_SET_CONTEXT, L"Set Context", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, THREAD_QUERY_INFORMATION, L"Query Information", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, THREAD_SET_INFORMATION, L"Set Information", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, THREAD_SET_THREAD_TOKEN, L"Set Thread Token", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, THREAD_IMPERSONATE, L"Impersonate", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, THREAD_DIRECT_IMPERSONATION, L"Direct Impersonation", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, THREAD_SET_LIMITED_INFORMATION, L"Set Limited Information", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, THREAD_QUERY_LIMITED_INFORMATION, L"Query Limited Information", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, THREAD_RESUME, L"Resume", SI_ACCESS_DEFAULT_FLAGS }
};

//
//Token Access Values
//
#define MAX_KNOWN_TOKEN_ACCESS_VALUE 9

static SI_ACCESS TokenAccessValues[MAX_KNOWN_TOKEN_ACCESS_VALUE] = {
    { &GUID_NULL, TOKEN_ASSIGN_PRIMARY, L"AssignPrimary", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, TOKEN_DUPLICATE, L"Duplicate", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, TOKEN_IMPERSONATE, L"Impersonate", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, TOKEN_QUERY, L"Query", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, TOKEN_QUERY_SOURCE, L"Query Source", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, TOKEN_ADJUST_PRIVILEGES, L"Adjust Privileges", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, TOKEN_ADJUST_GROUPS, L"Adjust Groups", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, TOKEN_ADJUST_DEFAULT, L"Adjust Default", SI_ACCESS_DEFAULT_FLAGS },
    { &GUID_NULL, TOKEN_ADJUST_SESSIONID, L"Adjust SessionId", SI_ACCESS_DEFAULT_FLAGS }
};
