/*******************************************************************************
*
*  (C) COPYRIGHT AUTHORS, 2015
*
*  TITLE:       EXTRASUSD.H
*
*  VERSION:     1.20
*
*  DATE:        23 July 2015
*
*  Common header file for Extras User Shared Data dialog.
*
* THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
* ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED
* TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
* PARTICULAR PURPOSE.
*
*******************************************************************************/

static LPWSTR T_PROCESSOR_FEATURES[] = {
	L"PF_FLOATING_POINT_PRECISION_ERRATA",
	L"PF_FLOATING_POINT_EMULATED",
	L"PF_COMPARE_EXCHANGE_DOUBLE",
	L"PF_MMX_INSTRUCTIONS_AVAILABLE",
	L"PF_PPC_MOVEMEM_64BIT_OK",
	L"PF_ALPHA_BYTE_INSTRUCTIONS",
	L"PF_XMMI_INSTRUCTIONS_AVAILABLE",
	L"PF_3DNOW_INSTRUCTIONS_AVAILABLE",
	L"PF_RDTSC_INSTRUCTION_AVAILABLE",
	L"PF_PAE_ENABLED",
	L"PF_XMMI64_INSTRUCTIONS_AVAILABLE",
	L"PF_SSE_DAZ_MODE_AVAILABLE",
	L"PF_NX_ENABLED",
	L"PF_SSE3_INSTRUCTIONS_AVAILABLE",
	L"PF_COMPARE_EXCHANGE128",
	L"PF_COMPARE64_EXCHANGE128",
	L"PF_CHANNELS_ENABLED",
	L"PF_XSAVE_ENABLED",
	L"PF_ARM_VFP_32_REGISTERS_AVAILABLE",
	L"PF_ARM_NEON_INSTRUCTIONS_AVAILABLE",
	L"PF_SECOND_LEVEL_ADDRESS_TRANSLATION",
	L"PF_VIRT_FIRMWARE_ENABLED",
	L"PF_RDWRFSGSBASE_AVAILABLE",
	L"PF_FASTFAIL_AVAILABLE",
	L"PF_ARM_DIVIDE_INSTRUCTION_AVAILABLE",
	L"PF_ARM_64BIT_LOADSTORE_ATOMIC",
	L"PF_ARM_EXTERNAL_CACHE_AVAILABLE",
	L"PF_ARM_FMAC_INSTRUCTIONS_AVAILABLE",
	L"PF_RDRAND_INSTRUCTION_AVAILABLE",
	L"PF_ARM_V8_INSTRUCTIONS_AVAILABLE",
	L"PF_ARM_V8_CRYPTO_INSTRUCTIONS_AVAILABLE",
	L"PF_ARM_V8_CRC32_INSTRUCTIONS_AVAILABLE",
	L"PF_RDTSCP_INSTRUCTION_AVAILABLE",
	L""
};

VOID extrasCreateUsdDialog(
	_In_ HWND hwndParent
	);
